### ISSUE TITLE
id_number

### ISSUE THREAD

**Issue by Dalesw2** [woodenphone/Derpibooru-dl#17]
derpibooru_dl-2014-11-4

2016-06-29 16:28:40,503 - DEBUG - Logging started.
2016-06-29 16:28:42,003 - DEBUG - API Key looks fine.
2016-06-29 16:28:42,082 - INFO - Attempting to resume any failed downloads.
2016-06-29 16:29:27,990 - DEBUG - Menu user input:'3'
2016-06-29 16:29:36,358 - DEBUG - Query: 'bugmom'
2016-06-29 16:29:36,359 - DEBUG - Starting search for tag: bugmom
2016-06-29 16:29:36,361 - DEBUG - Scanning page 1 for query: bugmom
2016-06-29 16:29:36,864 - CRITICAL - Unhandled exception!
2016-06-29 16:29:36,865 - CRITICAL - <type 'exceptions.KeyError'>
2016-06-29 16:29:36,865 - ERROR - 'id_number'
Traceback (most recent call last):
  File "<string>", line 1532, in <module>
  File "<string>", line 1515, in main
  File "<string>", line 1430, in console_menu
  File "<string>", line 1108, in process_query
  File "<string>", line 685, in search_for_query
  File "<string>", line 655, in load_search_page
KeyError: 'id_number'
2016-06-29 16:29:36,867 - INFO - Program finished.

**Comment by Apple240Bloom** [comment]
I really hope wooden is still around I'm lost without his little executable =(

**Comment by JoeyH3** [comment]
Derpibooru recently made some structural modifications to their database, and id_number no longer exists. I've submitted a PR that should work. If anyone wants to try running it from source and letting me know if it works/causes any unforseen issues, please feel free to.

**Comment by Dalesw2** [comment]
Is there a chance for a updated standalone?
