### ISSUE TITLE
Image' object has no attribute 'id_number'

### ISSUE THREAD

**Issue by Dalesw2** [woodenphone/Derpibooru-dl#20]
Window 7
Standalone:derpibooru_dl-2016-7-1b.exe

2016-07-01 20:51:25,275 - DEBUG - Logging started.
2016-07-01 20:51:26,519 - DEBUG - API Key looks fine.
2016-07-01 20:51:26,520 - INFO - Attempting to resume any failed downloads.
2016-07-01 20:51:37,655 - DEBUG - Menu user input:'3'
2016-07-01 20:51:42,358 - DEBUG - Query: 'bugmom'
2016-07-01 20:51:42,359 - DEBUG - Starting search for query: 'bugmom'
2016-07-01 20:51:42,375 - INFO - Starting new HTTPS connection (1): derpiboo.ru
2016-07-01 20:51:42,680 - DEBUG - "GET /search.json?perpage=50&sf=created_at&q=bugmom&key=FZskUzzse7oPtT1LPYpu&page=1&sd=desc HTTP/1.1" 200 None
2016-07-01 20:51:42,691 - CRITICAL - Unhandled exception!
2016-07-01 20:51:42,693 - CRITICAL - <type 'exceptions.AttributeError'>
2016-07-01 20:51:42,693 - ERROR - 'Image' object has no attribute 'id_number'
Traceback (most recent call last):
  File "derpibooru_dl.py", line 1415, in <module>
  File "derpibooru_dl.py", line 1398, in main
  File "derpibooru_dl.py", line 1313, in console_menu
  File "derpibooru_dl.py", line 991, in process_query
  File "derpibooru_dl.py", line 594, in search_for_query
AttributeError: 'Image' object has no attribute 'id_number'
2016-07-01 20:51:42,696 - INFO - Program finished.

**Comment by oblivion2k** [comment]
This error is fixed in the derpibooru_dl-2016-7-1 release. However there is another issue with that release, and I've opened another thread to work on that. #21

**Comment by citizenwolf** [comment]
I'm also having this problem; the latest standalone version of the exe (derpibooru_dl-2016-7-1b) keeps crashing every time i run a query. Is there a way to fix this issue?
![derp error](https://cloud.githubusercontent.com/assets/11688548/16896771/4dbd2ad4-4b95-11e6-95bd-5936318ec02f.png)

**Comment by mkody** [comment]
Duplicate to #22, use python in command line instead.
