### ISSUE TITLE
derpibooru_dl-2016-7-1b crashes

### ISSUE THREAD

**Issue by Gifkun** [woodenphone/Derpibooru-dl#25]
This version crashes in Windows 10 after an option is selected, it starts to work and then it closes. I have tried many different things from downloading a new version to editing the config files with notepad++. I have no idea why it doesn't work anymore.

P.S. I am using the premade exe version for windows

**Comment by mkody** [comment]
The pre-made EXE is broken. See #22

**Comment by Gifkun** [comment]
Are there any plans to create a working exe since i have tried to run the python script with no success.

**Comment by JoeyH3** [comment]
The reason why it doesn't work anymore is because a lot of scripts/applications using the "id_number" attribute in the API got borked when the site dropped that attribute in favor of "id"

I have a fork of this repo which I used to reflect the change. These changes are currently reflected in this repo, but I'm not sure why the release isn't working. You can try my release though, which works on my PC: https://github.com/JoeyH3/Derpibooru-dl/releases/tag/derpibooru_dl-2016-06-30

**Comment by Gifkun** [comment]
it works Thank you very much!

**Comment by citizenwolf** [comment]
@JoeyH3 Thank-you very much, your version of the exe (search option 3. at least!) works on my machine :) Tried several times trying to install/use the script version with python and i simply couldn't the dl to function properly :/ 

If anyone could provide us beginners with clear installation instructions that would be wonderful :) in the mean time though this exe is fantastic :)

**Comment by PlanetKiller** [comment]
@JoeyH3 
Generates 200 None when the tag has a space in it.

**Comment by oblivion2k** [comment]
@JoeyH3 Nice work man. Looks like you're better with compiling EXEs than I am.
If you want to fix the 200 None issue, take a look at my fork. Then you can compile it and upload it on your fork.

**Comment by Dalesw2** [comment]
Has the standalone version been updated to handle spaces yet?

**Comment by PlanetKiller** [comment]
I don't think so. I've been using option 3 and making a folder with the same format as the tags when using the space.
This folder has to be in the downloads folder.
Seems to work, but I haven't been using tags with spaces much.
Maybe JoeyH3's fork has the fix?

https://github.com/JoeyH3

**Comment by Dalesw2** [comment]
Is there a better guide to use python version?

**Comment by EpicLPer** [comment]
@JoeyH3  Awesome! :)

**Comment by JoeyH3** [comment]
@Dalesw2 it runs off python2, and I believe the only requirement is DerPyBooru

So download the code, make sure you have Python 2 installed. Run this command once:
> pip install derpybooru

Then to use the Pyhton version, it should just be:
> python derpibooru_dl.py

**Comment by JoeyH3** [comment]
@PlanetKiller I just tried option 3 with the tag "book fort" and it seemed to work fine for me

**Comment by Dalesw2** [comment]
I keep getting this?

C:\Users\Dale>pip install derpybooru
Collecting derpybooru
  Using cached DerPyBooru-0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\dale\appdata\local\temp\pip-build-b7iqyw\derpybooru\setup.p
y", line 6, in <module>
        import derpibooru
      File "derpibooru\__init__.py", line 27, in <module>
        from .search import Search
      File "derpibooru\search.py", line 29, in <module>
        from .request import get_images, url
      File "derpibooru\request.py", line 27, in <module>
        from requests import get, codes
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\dale\app
data\local\temp\pip-build-b7iqyw\derpybooru\

**Comment by JoeyH3** [comment]
@Dalesw2 Whoops... I forgot about that part... My bad

Derpibooru_dl only requires DerPyBooru, but DerPyBooru has it's own dependancy.

>pip install requests

THEN

>pip install derpybooru

**Comment by Dalesw2** [comment]
@JoeyH3 
thank you.

**Comment by CheshireKitten** [comment]
@JoeyH3 
Yours is nice and works except for queries with spaces in them. i tried replacing the spaces in the dl config with +,%20,_'s and none of them could "find results" though there should be/are they work in singular search with spaces{option 3) and manually typing them out, just not via option 4

**Comment by PlanetKiller** [comment]
Come in Book Fort, this is Red Lobster, glad I could help; over.
