### ISSUE TITLE
Unhandled expection, <type 'exceptions.AssertionError'> when downloading recently created

### ISSUE THREAD

**Issue by twisprkl** [woodenphone/Derpibooru-dl#26]
https://github.com/JoeyH3/Derpibooru-dl/releases/tag/derpibooru_dl-2016-06-30
I am using this version, and I'm constantly getting this error.

2016-09-15 00:38:29,122 - INFO - Program finished.
2016-09-15 00:42:20,032 - DEBUG - Logging started.
2016-09-15 00:42:22,351 - DEBUG - API Key looks fine.
2016-09-15 00:42:22,352 - INFO - Attempting to resume any failed downloads.
2016-09-15 00:42:23,061 - DEBUG - Menu user input:'1'
2016-09-15 00:42:23,062 - INFO - Now downloading the last week's submissions.
2016-09-15 00:42:23,062 - DEBUG - Getting ID of most recent submission...
2016-09-15 00:42:23,065 - INFO - Starting new HTTPS connection (1): derpiboo.ru
2016-09-15 00:42:24,578 - DEBUG - "GET /search.json?perpage=50&sf=created_at&q=%2A&key=~~~~~~~~~~~~~~&page=1&sd=desc HTTP/1.1" 200 None
2016-09-15 00:42:24,788 - DEBUG - Most recent submission ID:1249099
2016-09-15 00:42:24,789 - INFO - Downloading the last 7000 submissions. Starting at 1249099 and stopping at 1242099
2016-09-15 00:42:24,789 - CRITICAL - Unhandled exception!
2016-09-15 00:42:24,789 - CRITICAL - <type 'exceptions.AssertionError'>
2016-09-15 00:42:24,790 - ERROR - 
Traceback (most recent call last):
  File "derpibooru_dl.py", line 1414, in <module>
  File "derpibooru_dl.py", line 1397, in main
  File "derpibooru_dl.py", line 1300, in console_menu
  File "derpibooru_dl.py", line 901, in download_this_weeks_submissions
  File "derpibooru_dl.py", line 940, in download_range
AssertionError
2016-09-15 00:42:24,792 - INFO - Program finished.
2016-09-15 00:43:01,078 - DEBUG - Logging started.
2016-09-15 00:43:02,818 - DEBUG - API Key looks fine.
2016-09-15 00:43:02,819 - INFO - Attempting to resume any failed downloads.

**Comment by twisprkl** [comment]
And I tried using derpibooru_dl.py with python.

I think I'm getting a similar error.

2016-09-15 00:52:58,736 - DEBUG - Logging started.
2016-09-15 00:53:00,901 - DEBUG - API Key looks fine.
2016-09-15 00:53:00,903 - INFO - Attempting to resume any failed downloads.
2016-09-15 00:53:02,766 - DEBUG - Menu user input:'1'
2016-09-15 00:53:02,766 - INFO - Now downloading the last week's submissions.
2016-09-15 00:53:02,766 - DEBUG - Getting ID of most recent submission...
2016-09-15 00:53:02,772 - INFO - Starting new HTTPS connection (1): derpiboo.ru
2016-09-15 00:53:04,332 - DEBUG - "GET /search.json?perpage=50&sf=created_at&q=%2A&key=~~~~~~~~~~~&page=1&sd=desc HTTP/1.1" 200 None
2016-09-15 00:53:04,542 - DEBUG - Most recent submission ID:1249111
2016-09-15 00:53:04,542 - INFO - Downloading the last 7000 submissions. Starting at 1249111 and stopping at 1242111
2016-09-15 00:53:04,543 - CRITICAL - Unhandled exception!
2016-09-15 00:53:04,545 - CRITICAL - <type 'exceptions.AssertionError'>
2016-09-15 00:53:04,546 - ERROR - 
Traceback (most recent call last):
  File "D:\I\Derpibooru-dl-master\derpibooru_dl.py", line 1414, in <module>
    main()
  File "D:\I\Derpibooru-dl-master\derpibooru_dl.py", line 1397, in main
    console_menu(settings,input_file_list)
  File "D:\I\Derpibooru-dl-master\derpibooru_dl.py", line 1300, in console_menu
    download_this_weeks_submissions(settings)
  File "D:\I\Derpibooru-dl-master\derpibooru_dl.py", line 901, in download_this_weeks_submissions
    download_range(settings,latest_submission_id,finish_number)
  File "D:\I\Derpibooru-dl-master\derpibooru_dl.py", line 940, in download_range
    assert(finish_number <= 1000000)# less than 1 million, 634,101 submissions as of 23-5-2014
AssertionError
2016-09-15 00:53:04,549 - INFO - Program finished.

**Comment by apanx** [comment]
Edit line 940 and 954. Increase the number to over maximum image ID number.
