### ISSUE TITLE
Downloader no longer works

### ISSUE THREAD

**Issue by EpicLPer** [woodenphone/Derpibooru-dl#30]
When starting any download, no matter if weekly or by tag, all I get is this on various different computers

`2016-12-31 18:37:52,283 - DEBUG - Logging started.
derpibooru_dl.py:572: UserWarning: gzip transfer encoding is experimental!
2016-12-31 18:37:53,141 - DEBUG - API Key looks fine.
2016-12-31 18:37:53,141 - INFO - Attempting to resume any failed downloads.
1. Download the last week or so's submissions.
2. Enter and download a range of submission IDs.
3. Enter and download the results of a search query
4. Download the results of each query and submission ID in the download list
5. Run downloads automatically based on settings file.
X. Exit.
Enter an option then press return
1
2016-12-31 18:38:06,667 - DEBUG - Menu user input:'1'
2016-12-31 18:38:06,668 - INFO - Now downloading the last week's submissions.
2016-12-31 18:38:06,668 - DEBUG - Getting ID of most recent submission...
2016-12-31 18:38:06,673 - INFO - Starting new HTTPS connection (1): derpiboo.ru
2016-12-31 18:38:06,904 - DEBUG - "GET /search.json?perpage=50&sf=created_at&q=%2A&key=tzk685pF5YqVHmuj9p3w&page=1&sd=desc HTTP/1.1" 200 None
2016-12-31 18:38:06,907 - CRITICAL - Unhandled exception!
2016-12-31 18:38:06,908 - CRITICAL - <type 'exceptions.ValueError'>
2016-12-31 18:38:06,908 - ERROR - No JSON object could be decoded
Traceback (most recent call last):
  File "derpibooru_dl.py", line 1415, in <module>
  File "derpibooru_dl.py", line 1398, in main
  File "derpibooru_dl.py", line 1301, in console_menu
  File "derpibooru_dl.py", line 897, in download_this_weeks_submissions
  File "derpibooru_dl.py", line 884, in get_latest_submission_id
  File "site-packages\derpibooru\search.py", line 184, in next
  File "site-packages\derpibooru\request.py", line 74, in get_images
  File "site-packages\derpibooru\request.py", line 56, in request
  File "site-packages\requests\models.py", line 812, in json
  File "json\__init__.py", line 339, in loads
  File "json\decoder.py", line 364, in decode
  File "json\decoder.py", line 382, in raw_decode
ValueError: No JSON object could be decoded
2016-12-31 18:38:06,910 - INFO - Program finished.`

**Comment by liamwhite** [comment]
Just an FYI, I reset your API key for you.

**Comment by JoeyH3** [comment]
First off, try this version of the app. I can confirm it works: https://github.com/woodenphone/Derpibooru-dl/files/512491/derpibooru_dl-2016-10-5.zip

Second, even though I see you already edited your original post to remove your API key, you're forgetting that the email notification (for those who are subscribed to this project) contains the original post, key included. I asked one of the sysadmins to reset your API key since it's as good as compromised, so be sure to get your new one before trying again.

**Comment by EpicLPer** [comment]
Thanks @liamwhite @JoeyH3, I saw it too late yeah... I looked everywhere but forgot to check the URL.

Anyways, I'll give it a try, thanks!

**Comment by EpicLPer** [comment]
Okay well the version @JoeyH3 posted does work tho I got a bunch of errors for the first few pics, plus if the API key has a "_" in it (which mine has now) it will simply throw this at the beginning

```
2017-01-01 15:34:35,723 - ERROR - API key contains invalid characters.
2017-01-01 15:34:35,723 - DEBUG - Invalid characters found: set(['_'])
2017-01-01 15:34:35,723 - ERROR - Problem in first 5 characters
2017-01-01 15:34:36,601 - WARNING - API key looks invalid!
```

**Comment by woodenphone** [comment]
Wow this project is a mess that I do not understand anymore.
Fixing this may take a while.
